import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ProviderNextui } from "../components/shared/ProviderNextui";
import React from "react";

import ProviderTrpc from "@/components/shared/ProviderTrpc";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className="dark"
    >
      <body className={inter.className}>
        <ProviderTrpc>
          <ProviderNextui>{children}</ProviderNextui>
        </ProviderTrpc>
      </body>
    </html>
  );
}
