import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ProviderNextui } from "../components/shared/ProviderNextui";
import React from "react";
import SessionProvider from "@/components/shared/SessionProvider";
import { getServerSession } from "next-auth";
import ProviderTrpc from "@/components/shared/ProviderTrpc";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html
      lang="en"
      className="dark"
    >
      <body className={inter.className}>
        <SessionProvider session={session}>
          <ProviderTrpc>
            <ProviderNextui>{children}</ProviderNextui>
          </ProviderTrpc>
        </SessionProvider>
      </body>
    </html>
  );
}
